[project]
name = 'tiny-market-2'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.sip009-nft]
path = 'contracts/sip009-nft.clar'
clarity_version = 2
epoch = 2.5

[contracts.sip010-token]
path = 'contracts/sip010-token.clar'
clarity_version = 2
epoch = 2.5

[contracts.tiny-market]
path = 'contracts/tiny-market.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
